blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/superwerker/superwerker/discussions/new
    about: Please share ideas and feature requests as discussions!
